#!/bin/bash
# TurboGears OpenShift post-build deploy configuration

set -e
export PYTHON=python
export PATH=$PATH:~/$PYTHON/virtenv/venv/bin/
export PYTHON_EGG_CACHE=~/$PYTHON/virtenv/venv/lib/python3.3/site-packages

source ~/$PYTHON/virtenv/venv/bin/activate

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
then
    echo 1>&2
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push"
1>&2
    echo 1>&2
    echo 1>&2
    exit 5
fi

cd $OPENSHIFT_REPO_DIR/wsgi/tg2app

# Initialize our database once
if [ ! -e $OPENSHIFT_DATA_DIR/DB_INITIALIZED ]; then
    echo "Initializing database"
    gearbox setup-app -c development.ini
    touch $OPENSHIFT_DATA_DIR/DB_INITIALIZED
# else
#     echo "Upgrading database"
#     gearbox migrate upgrade
fi

# Run the test suite automatically
# At the moment failure does not prevent the code from getting deployed
# echo "Running the test suite"
# unset OPENSHIFT_APP_NAME
# nosetests -q
